// File generated by the FlutterFire CLI.
// DO NOT EDIT. This file is automatically generated by running:
// flutterfire configure
//
// To regenerate this file, run:
// flutterfire configure
//
// Once you have your firebase_options.dart file generated,
// this file will contain your Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALpbjsm2UtO1d8pkR8zK9UU75W5CZLjRw',
    appId: '1:842043851979:android:42b6203fe72596b448c74e',
    messagingSenderId: '842043851979',
    projectId: 'eharvest-3f31c',
    storageBucket: 'eharvest-3f31c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2RXai-_sbTQX1_U2wOTTu3E2C7RzU7Js',
    appId: '1:842043851979:ios:3c8ba08a50fab58248c74e',
    messagingSenderId: '842043851979',
    projectId: 'eharvest-3f31c',
    storageBucket: 'eharvest-3f31c.firebasestorage.app',
    iosBundleId: 'com.example.eharvestMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvh5_9g1Q022XWK5pnebfmW2lYr6QVEQo',
    appId: '1:842043851979:web:1864e8987f55efad48c74e',
    messagingSenderId: '842043851979',
    projectId: 'eharvest-3f31c',
    authDomain: 'eharvest-3f31c.firebaseapp.com',
    storageBucket: 'eharvest-3f31c.firebasestorage.app',
    measurementId: 'G-N0YXV6VTJ4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2RXai-_sbTQX1_U2wOTTu3E2C7RzU7Js',
    appId: '1:842043851979:ios:3c8ba08a50fab58248c74e',
    messagingSenderId: '842043851979',
    projectId: 'eharvest-3f31c',
    storageBucket: 'eharvest-3f31c.firebasestorage.app',
    iosBundleId: 'com.example.eharvestMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvh5_9g1Q022XWK5pnebfmW2lYr6QVEQo',
    appId: '1:842043851979:web:23466b811f2300c748c74e',
    messagingSenderId: '842043851979',
    projectId: 'eharvest-3f31c',
    authDomain: 'eharvest-3f31c.firebaseapp.com',
    storageBucket: 'eharvest-3f31c.firebasestorage.app',
    measurementId: 'G-55DZ7F41FP',
  );

}